### ISSUE TITLE
Normalize URL configs

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#25]
Most of our URL regular expressions are messed up right now, and match things past where they are supposed to. For example, [`/program/new/foo/bar`](http://ourjseditor.com/program/new/foo/bar) is matched by the new program regular expression.

**Comment by Mesolatido** [comment]
I'm still looking for the file to add these expressions to, but I think the following regular expressions might work out in the long run: 

**Admin**: `^admin/(\w+)/$` (more restrictive in it's matches)
**Account**: `^account/(settings/|profile/)?$`
**API**: `^api/` (kept the same because I'm not sure how deep api urls will go)
**Programs**: `^program/(new|[-_\w]{6})/$` (Added '$' to the end, still accepts 6 character program ids)
**User**: `^user/(\w+)/$`
